market/urls.py
from django.urls import path
from . import views

app_name = 'market'

urlpatterns = [
    path('order_list', views.OrderListView.as_view(), name='order_list'),
    path('goods_list', views.GoodsListView.as_view(), name='goods_list'),
    path('ordered_list/<str:ordered_by>', views.OrderedListView.as_view(), name='ordered_list'),
    path('order_formset', views.add_order, name='order_formset'),
    path('testpage', views.TestView.as_view(), name='testpage'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
]

market/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

# 商品を表すモデル
class Goods(models.Model):
    name = models.CharField(
        verbose_name='商品名',
        max_length=200
    )
    price = models.IntegerField(
        verbose_name='単価'
    )
    description = models.TextField(
        verbose_name='説明',
        max_length=500
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('商品')
        verbose_name_plural = ('商品')

# 注文を表すモデル
class Order(models.Model):
    date = models.DateTimeField(
        verbose_name='注文日時',
        auto_now=True
    )
    goods = models.ForeignKey(
        'Goods',
        verbose_name='注文商品',
        on_delete=models.CASCADE
    )
    amount = models.IntegerField(
        verbose_name='注文数'
    )
    
    ordered_by = models.CharField(
        verbose_name='注文者',
        max_length=50
    )

    def __str__(self):
        return str(self.ordered_by) + ': ' + str(self.goods) + '*' + str(self.amount)
    
    class Meta:
        verbose_name = ('注文')
        verbose_name_plural = ('注文')

market/forms.py
from django import forms
from .models import Order, Goods

# Orderを登録するためのフォーム
class OrderCreateForm(forms.ModelForm):
    # モデルの入力対象フィールドを設定
    class Meta:
        model = Order
        fields = ('goods', 'amount', 'ordered_by')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['goods'].disabled = True # goodsフィールドを編集不可にする
        self.fields['amount'].widget.attrs.update({'class': 'amountfield'})

    # amountが0より大きな値でない時はエラーを出す
    # バリデーション用関数はclean_[要素名]で関数定義
    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount <= 0:
            raise forms.ValidationError('数量は1以上の整数にしてください')
        return amount

# モデルフォームセット
# フォームはGoodsのレコードの数だけ作成する
OrderCreateFormSet = forms.modelformset_factory(
    Order, form=OrderCreateForm, extra=Goods.objects.all().count()
)

market/views.py
from typing import Any, Dict
from django.shortcuts import render

# Create your views here.
from django.views import generic
from django.shortcuts import render
from django.http import JsonResponse
from .models import Goods, Order
from .forms import OrderCreateFormSet

# Orderを複数登録するための関数ビュー
def add_order(request):
    # 新規登録用のformだけを用意する(queryset=Order.objects.none())
    formset = OrderCreateFormSet(
        request.POST or None,
        queryset=Order.objects.none(),
        initial=[{'goods': g} for g in Goods.objects.all()],
    )
    
    # 送信ボタンが押された際の処理
    if request.method == 'POST':
        if formset.is_valid():
            print('バリデーションOK')
            formset.save()
            data = {
                'result': 'OK',
                'msg': '注文成功：5秒後にページを切り替えます…',
            }
            return JsonResponse(data)
        else: # 入力内容に不備がある
            print('バリデーションNG')
            data = {
                'result': 'NG',
                'msg': '注文失敗：個数は1以上の値を設定し、個数を設定した欄には注文者も設定してください',
            }
            return JsonResponse(data)
    
    # テンプレートに渡すコンテキストを設定
    # 二つのイテラブルを同じインデックスで参照したいのでzipする
    context = {
        'formset': formset, # フォームの個数を|lengthで把握するため
        'obj_list': zip(formset, Goods.objects.all()),
    }

    return render(request, 'market/order_formset.html', context)

# 注文一覧ビュー
class OrderListView(generic.ListView):
    template_name = 'market/order_list.html'
    # Orderモデルのうち、注文者だけを取り出し、重複を削除し、テンプレートに渡す
    queryset = Order.objects.values('ordered_by').order_by('ordered_by').distinct()

# 商品一覧ビュー
class GoodsListView(generic.ListView):
    template_name = 'market/goods_list.html'
    model = Goods

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # OrderモデルとGoodsモデルを(イテレータとして)すべて取得し、order_listとしてテンプレートに渡す
        order_obj = Order.objects.all()
        context['order_list'] = order_obj
        return context

# 注文詳細ビュー
class OrderedListView(generic.ListView):
    template_name = 'market/ordered_list.html'
    context_object_name = 'order_list'

    # urlから受け取ったパラメータを使ってOrderをフィルタリング
    def get_queryset(self):
        param = self.kwargs['ordered_by']
        return Order.objects.filter(ordered_by=param)

    # urlから受け取ったパラメータ（注文者の名前）をコンテキストに追加
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        goods_obj = Goods.objects.all()
        context['ordered'] = self.kwargs['ordered_by']
        context['goods_list'] = goods_obj
        return context
    
    # javascript側からのPOST送信をもとに該当するOrderのデータを削除する
    def post(self, request, **kwargs):
        print('order id posted')
        # リスト形式で削除対象Orderのidを取得
        id_list = request.POST.getlist('delete_order')
        print(id_list)
        for id in id_list:
            Order.objects.get(id=id).delete()
        data = {
            'result': 'OK',
            'msg': 'データの削除が完了しました。ページを更新します…',
        }
        return JsonResponse(data)

# いろいろ試すためのビュー
class TestView(generic.TemplateView):
    template_name = 'market/testpage.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        goods_obj = Goods.objects.all()
        ctx['goods_list'] = goods_obj
        return ctx
    

templates/market/base.html
<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>通販サイト……のようなもの</title>
    </head>

    <body>
        <!-- ナビゲーションバーをつくる -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <span class="navbar-brand">メニュー</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'market:order_formset' %}">注文する</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'market:order_list' %}">注文者リスト</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'market:goods_list' %}">商品リスト</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- 継承先コンテンツは左右のマージンを少しとる -->
        <div class="mx-4">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
    </body>
</html>

templates/market/goods_list.html
{% extends "market/base.html" %}
{% block content %}

<h2>商品一覧</h2>

<table class="table table-bordered border-dark" style="width: 600px">
    <thead class="table-active">
        <tr>
            <th>商品名</th>
            <th>単価</th>
            <th>商品説明</th>
        </tr>
    </thead>
    <tbody>
        <!-- views.pyでmodel=Goodとしたので、goods_listとしてGoodsのリストが渡される -->
        {% for goods in goods_list %}
        <tr>
            <td>{{ goods.name }}</td>
            <td>￥{{ goods.price }}</td>
            <td>{{ goods.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/market/order_formset.html
{% extends "market/base.html" %}
{% block content %}
{% load static %}

<!-- amountの入力フィールドだけ幅を狭くしておく -->
<style>
    .amountfield {
        width: 80px;
    }
</style>

<div>
    <h2>注文する</h2>

    <form action="" method="post" id="order_formset">
        <table class="table">
            <thead>
                <tr>
                    <th>商品名</th>
                    <th>単価</th>
                    <th>個数</th>
                    <th>注文者</th>
                </tr>
            </thead>
            <tbody>
                <!-- zipされたコンテキストからそれぞれ取り出す -->
                {% for form, goods in obj_list %}
                <tr>
                    {% for field in form %}
                    {% if forloop.counter0 == 1 %}
                    <td>￥{{ goods.price }}</td>
                    <td>{{ field }}</td>
                    {% else %}
                    <td>{{ field }}</td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {{ formset.management_form }}
        {% csrf_token %}
        
        <button id="ajax_order_validation" type="submit" class="btn btn-primary my-3">送信</button>
    </form>

    <div id="messages">
        <!-- バリデーションエラー時、ここにメッセージを表示する -->
    </div>

    <!-- 静的ファイル内ではテンプレートタグを使用できない
        そこで、静的ファイルを呼び出す前にコンテキストを変数に入れておく -->
    <script>
        let formset_count = {{ formset|length|escape|safe }};
        let validation_url = "{% url 'market:order_formset' %}";
        let redirect_url = "{% url 'market:order_list' %}";
    </script>
    <script src="{% static 'market/form_manage.js' %}"></script>

    <div class="my-3">
        <p>オプション：注文者を一括設定する（要Javascript）</p>
        <label for="order_name">入力欄</label>
        <input type="text" id="order_name">
        <button onClick="setName(0);" class="btn btn-primary">すべて設定</button>
        <button onClick="setName(1);" class="btn btn-primary">個数指定済みのものに設定</button>
    </div>
</div>

{% endblock %}

templates/market/order_list.html
{% extends "market/base.html" %}
{% block content %}
{% load extra_tags %}

<h2>注文者リスト</h2>

<table class="table">
    <tbody>
        {% for order in order_list %}
        <tr>
            <td><a href="ordered_list/{{ order.ordered_by }}">{{ order.ordered_by }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/market/ordered_list.html
{% extends "market/base.html" %}
{% block content %}

{% load extra_tags %}
{% load humanize %}
{% load static %}

<h2>{{ ordered }}の注文詳細</h2>

<div>
    商品名でフィルタリング：
    <select id="goods_select">
        <option value="すべて" id="all">すべて</option>
        {% for goods in goods_list %}
        <option value="{{ goods.name }}" id="{{ goods.id }}">{{ goods.name }}</option>
        {% endfor %}
    </select>
</div>

<form action="", method="post", id="delete_order_form">
    <div class="my-3">
        注文取消し：
        <button id="all-check-btn" class="btn btn-primary">すべてチェック</button>
        <button id="delete_order_btn" class="btn btn-danger" type="submit">注文を取り消す</button>
    </div>
    <!-- データ削除通知を表示する領域 -->
    <div id="delete_msg"></div>

    <table class="table table-sm table-hover border-top mt-4" id="order_table">
        <thead>
            <tr>
                <th class="border-end">商品名</th>
                <th class="border-end text-center">個数</th>
                <th class="border-end text-center">金額</th>
                <th>　日付</th>
            </tr>
        </thead>
        {% for order in order_list %}
        <tr style="display: table-row">
            <td class="border-end" style="width: 20%">
                <input 
                    type="checkbox"
                    id="delete_order_{{ forloop.counter }}"
                    name="delete_order"
                    value="{{ order.id }}"
                />
                <label for="delete_order_{{ forloop.counter }}">{{ order.goods.name }}</label>
            </td>
            <td class="border-end" align="right" style="width: 10%">{{ order.amount | intcomma }}個</td>
            <td class="border-end" align="right" style="width: 10%">￥{{ order.goods.price | multiply:order.amount | escape | intcomma }}</td>
            <td>　{{ order.date }}</td>
        </tr>
        {% endfor %}
    </table>
</form>

<a href="{% url 'market:order_list' %}">注文者一覧に戻る</a>

<script src="{% static 'market/order_manage.js' %}"></script>

{% endblock %}

templates/market/testpage.html
{% extends "market/base.html" %}
{% block content %}

<h3>砂場</h3>
<form action="" method="POST">
    <table class="table">
        <thead>
            <th>商品名</th>
            <th>単価</th>
            <th>個数</th>
        </thead>
        <tbody>
            {% for goods in goods_list %}
            <tr>
                <td>{{ goods.name }}</td>
                <td>￥{{ goods.price }}</td>
                <td><input type="number"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="my-3">
        <p>注文者：<input type="text"></p>
    </div>
    <button type="submit" class="btn btn-primary my-3">送信</button>
    {% csrf_token %}
</form>

{% endblock %}